name: Test CI
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test action
    runs-on: generic-s
    if: "contains(github.event.head_commit.message, 'Deploy new version')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - uses: ./
        with:
          milliseconds: 1000
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
